error.throw;
resume;
:error;
resume;